"""add psswd column to user.

Revision ID: 7d5decfb4997
Revises: 89cb4ef18210
Create Date: 2024-06-21 16:09:34.259211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5decfb4997'
down_revision: Union[str, None] = '89cb4ef18210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('psswd', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'psswd')
    # ### end Alembic commands ###
